### ISSUE TITLE
If STK approves an application update status in card. (Collapse)

### ISSUE THREAD

**Issue by aylingorgun** [acikkaynak/ben-yaparim#39]

**Comment by selensr** [comment]
@betulerkoc this issue must have been resolved, please check the main branch

**Comment by betulerkoc** [comment]
@selensr not resolved for collapse yet. For details please check design:

![image](https://user-images.githubusercontent.com/40780338/219303521-1c0102a3-80a2-453f-abed-c0e080a30e55.png)
